create table trace
(
    ts timestamp(25, 3),
	eqp_id varchar(max),
	module_name varchar(max),
	lot_cd varchar(max),
	lot_id varchar(max),
	slot_id varchar(max),
	product_id varchar(max),
	oper_id varchar(max),
	oper_desc varchar(max),
	recipe_id varchar(max),
	ppid varchar(max),
	step_id varchar(max),
	step_name varchar(max),
	param_name array(0),
	param_alias array(0),
	param_svid array(0),
	param_value array(0),
	batch_id varchar(max),	
	batch_type varchar(max),
	"zone" varchar(max),
	start_dtts timestamp(25,3),
	create_dtts timestamp(25,3),
	org_wf_id varchar(max),
	alias_lot_id varchar(max),
	fdc_lot_cd varchar(max),
	target array(0),
	lsl array(0),
	lcl array(0),
	ucl array(0),
	usl array(0),
	spec_model_name array(0),
	dt varchar(max),
	fab varchar(max)
);

create table trace_flatten
(
    ts timestamp(25, 3),
	eqp_id varchar(max),
	module_name varchar(max),
	lot_cd varchar(max),
	lot_id varchar(max),
	slot_id varchar(max),
	product_id varchar(max),
	oper_id varchar(max),
	oper_desc varchar(max),
	recipe_id varchar(max),
	ppid varchar(max),
	step_id varchar(max),
	step_name varchar(max),
	param_name varchar(max),
	param_alias varchar(max),
	param_svid varchar(max),
	param_value varchar(max),
	batch_id varchar(max),
	batch_type varchar(max),
	"zone" varchar(max),
	start_dtts timestamp(25,3),
	create_dtts timestamp(25,3),
	org_wf_id varchar(max),
	alias_lot_id varchar(max),
	fdc_lot_cd varchar(max),
	target varchar(max),
	lsl varchar(max),
	lcl varchar(max),
	ucl varchar(max),
	usl varchar(max),
	spec_model_name varchar(max),
	dt varchar(max),
	fab varchar(max)
);

create table summary
(
    eqp_id varchar(max) ,
	module_name varchar(max),
	lot_id varchar(max),
	slot_id varchar(max),
	oper_id varchar(max),
	oper_desc varchar(max),
	recipe_id varchar(max),
	ppid varchar(max),
	step_id varchar(max),
	step_name varchar(max),
	end_time timestamp(25,3),
	batch_id varchar(max),
	batch_type varchar(max),
	org_wf_id varchar(max),
	alias_lot_id varchar(max),
	param_name array(0),
	param_alias array(0),
	param_svid array(0),
	max_val array(0),
	min_val array(0),
	mean_val array(0),
	stddev_val array(0),
	range_val array(0),
	median_val array(0),
	integral_val array(0),
	slope_val array(0),
	p05_val array(0),
	p10_val array(0),
	p90_val array(0),
	p95_val array(0),
	count_val array(0),
	sumsq_val array(0),
	step_merge_yn array(0),
	fdc_lot_cd varchar(max),
	dt varchar(max),
	fab varchar(max),
	lot_cd varchar(max),
	etl_start_dtts varchar(max),
	etl_end_dtts varchar(max),
	start_time array(0)
);

